method: grid
name: vae-bottlenecks-sweep
parameters:
  data:
    values: ["mnist", "medmnist"]
  model:
    values: ["gaussian", "dirichlet", "cc"]
  seed:
    values: [1, 2]
command:
  - ${env}
  - python
  - -m
  - src.deep_proj.train
  - --config-name
  - base_config           # your normal (non-sweep) Hydra config, e.g. configs/base_config.yaml
  - dataset=${data}
  - model=${model}
  - seed=${seed}
