#configs/wandb_sweep_config.yaml
#program: src/deep_proj/train.py   # not strictly needed since we use `command`, but nice metadata

#TO RUN SWEEP TYPE IN TERMINAL: wandb sweep configs/wandb_sweep_config.yaml
#THEN TYPE: wandb agent <sweep_id>


entity: spicy-mlops
project: vae-bottlenecks-final-final
name: vae-bottlenecks-final-final
method: grid

parameters:
  dataset:
    values: ["mnist", "medmnist"]
  model_name:
    values: ["dirichlet", "gaussian", "cc"]    #, "cc"]
  lr:
    values: [3e-4,5e-4,7e-4]   #, 0.001, 0.003]
  latent_dim:
    values: [3,5,8] #, 50]  #, 50]


command:
  - ${env}
  - python
  - -m
  - src.deep_proj.train
  - --config-name
  - base_config

